apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${serviceName}-mariadb
  namespace: ${environment}-${serviceName}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        ports:
        - containerPort: 3306
        resources:
          requests:
            memory: "2.5Gi"
            cpu: "1"
          limits:
            memory: "5Gi"
            cpu: "2"
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${serviceName}-mariadb-secret
              key: MARIADB_ROOT_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            secretKeyRef:
              name: ${serviceName}-mariadb-secret
              key: MARIADB_DATABASE
        - name: MARIADB_USER
          valueFrom:
            secretKeyRef:
              name: ${serviceName}-mariadb-secret
              key: MARIADB_USER
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ${serviceName}-mariadb-secret
              key: MARIADB_PASSWORD
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: ${serviceName}-mariadb-pvc
