apiVersion: v1
kind: Service
metadata:
  name: ${serviceName}-mariadb
  namespace: ${environment}-${serviceName}
spec:
  selector:
    app: mariadb
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
  clusterIP: None # Optional: For headless service, remove if not required
