apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${serviceName}-${environment}-new-1
  namespace: ${environment}-${serviceName}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${letEncryptEmail}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: ${serviceName}-${environment}-key-1
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            namespace: ${environment}-${serviceName}
            key: api-token
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${serviceName}-${environment}-new-2
  namespace: ${environment}-${serviceName}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${letEncryptEmail}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: ${serviceName}-${environment}-key-2
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            namespace: ${environment}-${serviceName}
            key: api-token

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${serviceName}-${environment}-new-3
  namespace: ${environment}-${serviceName}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${letEncryptEmail}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: ${serviceName}-${environment}-key-3
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            namespace: ${environment}-${serviceName}
            key: api-token

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ${serviceName}-${environment}-new-4
  namespace: ${environment}-${serviceName}
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: ${letEncryptEmail}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: ${serviceName}-${environment}-key-4
    # Add a single challenge solver, HTTP01 using nginx
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            namespace: ${environment}-${serviceName}
            key: api-token
