apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  metadata:
  name: ${serviceName}-postgresql
  namespace: ${environment}-${serviceName}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
