apiVersion: v1
kind: Service
metadata:
  name: ${serviceName}-postgres
  namespace: ${environment}-${serviceName}
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432