apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${serviceName}-mail-server-pvc
  namespace: ${environment}-${serviceName}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 18Gi
