apiVersion: v1
kind: Service
metadata:
  name: ${serviceName}-mongodb-service
  namespace: ${environment}-${serviceName}
spec:
  clusterIP: None
  selector:
    app: mongodb
  ports:
    - port: 27017