apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${serviceName}-mongodb-pv
  namespace: ${environment}-${serviceName}
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/mongodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${serviceName}-mongodb-pvc
  namespace: ${environment}-${serviceName}
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi