apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ${serviceName}-mongodb
  namespace: ${environment}-${serviceName}
spec:
  serviceName: "${serviceName}-mongodb-service"
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        command:
        - mongod
        - "--bind_ip_all"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        - name: keyfile
          mountPath: /etc/mongodb-keyfile
          readOnly: true
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: keyfile
        secret:
          secretName: ${serviceName}-mongodb-keyfile
          defaultMode: 0400  
  volumeClaimTemplates:
  - metadata:
      name: mongodb-storage
      namespace: ${environment}-${serviceName}
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi