apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${serviceName}-webserver
  namespace: ${environment}-${serviceName}
  labels:
    tier: backend
    layer: webserver
spec:
  replicas: ${deploymentReplicas}
  selector:
    matchLabels:
      tier: backend
      layer: webserver
  template:
    metadata:
      labels:
        tier: backend
        layer: webserver
    spec:
      containers:
        - name: webserver
          image: ${DOCKER_REGISTRY}/${serviceName}_web:v${imageVersion}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: ${serviceName}
            - secretRef:
                name: ${serviceName}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${serviceName}-worker
  namespace: ${environment}-${serviceName}
  labels:
    tier: backend
    layer: worker
spec:
  replicas: ${deploymentReplicas}
  selector:
    matchLabels:
      tier: backend
      layer: worker
  template:
    metadata:
      labels:
        tier: backend
        layer: worker
    spec:
      containers:
        - name: worker
          image: ${DOCKER_REGISTRY}/${serviceName}_worker:v${imageVersion}
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: ${serviceName}
            - secretRef:
                name: ${serviceName}