apiVersion: v1
kind: Service
metadata:
  name: ${serviceName}-websocket
  namespace: ${environment}-${serviceName}
spec:
  selector:
    tier: backend
    layer: websocket
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001

