apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${serviceName}-redis
  namespace: ${environment}-${serviceName}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      # We are starting with 1GB. We can always increase it later.
      storage: 4Gi
